/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LexicalNodes_1BF9FF18".
 */
export type LexicalNodes_1BF9FF18 =
  | SerializedTextNode
  | SerializedTabNode
  | SerializedLineBreakNode
  | SerializedParagraphNode<LexicalNodes_1BF9FF18>
  | SerializedInlineBlockNode<ShopValue>
  | SerializedAutoLinkNode<LexicalNodes_1BF9FF18, LexicalLinkFields>
  | SerializedLinkNode<LexicalNodes_1BF9FF18, LexicalLinkFields>
  | SerializedListNode<LexicalNodes_1BF9FF18>
  | SerializedListItemNode<LexicalNodes_1BF9FF18>;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LexicalNodes_92587427".
 */
export type LexicalNodes_92587427 =
  | SerializedTextNode
  | SerializedTabNode
  | SerializedLineBreakNode
  | SerializedParagraphNode<LexicalNodes_92587427>
  | SerializedBlockNode<Boxed>
  | SerializedInlineBlockNode<ShopValue>
  | SerializedHeadingNode<LexicalNodes_92587427, 'h3'>
  | SerializedAutoLinkNode<LexicalNodes_92587427, LexicalLinkFields>
  | SerializedLinkNode<LexicalNodes_92587427, LexicalLinkFields>
  | SerializedListNode<LexicalNodes_92587427>
  | SerializedListItemNode<LexicalNodes_92587427>;

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    awards: Award;
    'legal-documents': LegalDocument;
    families: Family;
    'product-stories': ProductStory;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    awards: AwardsSelect<false> | AwardsSelect<true>;
    'legal-documents': LegalDocumentsSelect<false> | LegalDocumentsSelect<true>;
    families: FamiliesSelect<false> | FamiliesSelect<true>;
    'product-stories': ProductStoriesSelect<false> | ProductStoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    shop: Shop;
    'product-page': ProductPage;
    estate: Estate;
    orchard: Orchard;
    weddings: Wedding;
    help: Help;
    search: Search;
    'order-confirmation': OrderConfirmation;
    header: Header;
    footer: Footer;
    common: Common;
    settings: Setting;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    shop: ShopSelect<false> | ShopSelect<true>;
    'product-page': ProductPageSelect<false> | ProductPageSelect<true>;
    estate: EstateSelect<false> | EstateSelect<true>;
    orchard: OrchardSelect<false> | OrchardSelect<true>;
    weddings: WeddingsSelect<false> | WeddingsSelect<true>;
    help: HelpSelect<false> | HelpSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'order-confirmation': OrderConfirmationSelect<false> | OrderConfirmationSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    common: CommonSelect<false> | CommonSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
    'collection-query': CollectionQueryWidget;
    activity: ActivityWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Ce que montre la photo, pour qui ne la voit pas.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    w480?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    w960?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    w1440?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    w2048?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards".
 */
export interface Award {
  id: number;
  year: number;
  title: string;
  /**
   * Sur la page d’accueil.
   */
  summary: string;
  /**
   * Sur la page du domaine.
   */
  detail: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-documents".
 */
export interface LegalDocument {
  id: number;
  document: 'legal-notice' | 'terms-of-sale' | 'terms-of-use' | 'privacy';
  title: string;
  /**
   * Changez-la à chaque modification : c’est la version que les clients acceptent.
   */
  effectiveDate: string;
  preamble?: LexicalRichText<LexicalNodes_92587427> | null;
  /**
   * Numérotés dans l’ordre.
   */
  articles?:
    | {
        title: string;
        /**
         * Pour y mener directement : « order » pour /terms-of-sale#order. En anglais, sans espaces.
         */
        anchor: string;
        content: LexicalRichText<LexicalNodes_92587427>;
        id?: string | null;
      }[]
    | null;
  appendices?:
    | {
        title: string;
        /**
         * Pour y mener directement : « order » pour /terms-of-sale#order. En anglais, sans espaces.
         */
        anchor: string;
        content: LexicalRichText<LexicalNodes_92587427>;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "families".
 */
export interface Family {
  id: number;
  category: string;
  /**
   * Celui de Medusa, repris à chaque enregistrement.
   */
  name?: string | null;
  photo?: (number | null) | Media;
  introduction?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-stories".
 */
export interface ProductStory {
  id: number;
  product: string;
  /**
   * Celui de Medusa, repris à chaque enregistrement.
   */
  name?: string | null;
  making?: string | null;
  steps?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'awards';
        value: number | Award;
      } | null)
    | ({
        relationTo: 'legal-documents';
        value: number | LegalDocument;
      } | null)
    | ({
        relationTo: 'families';
        value: number | Family;
      } | null)
    | ({
        relationTo: 'product-stories';
        value: number | ProductStory;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        w480?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        w960?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        w1440?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        w2048?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards_select".
 */
export interface AwardsSelect<T extends boolean = true> {
  year?: T;
  title?: T;
  summary?: T;
  detail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-documents_select".
 */
export interface LegalDocumentsSelect<T extends boolean = true> {
  document?: T;
  title?: T;
  effectiveDate?: T;
  preamble?: T;
  articles?:
    | T
    | {
        title?: T;
        anchor?: T;
        content?: T;
        id?: T;
      };
  appendices?:
    | T
    | {
        title?: T;
        anchor?: T;
        content?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "families_select".
 */
export interface FamiliesSelect<T extends boolean = true> {
  category?: T;
  name?: T;
  photo?: T;
  introduction?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-stories_select".
 */
export interface ProductStoriesSelect<T extends boolean = true> {
  product?: T;
  name?: T;
  making?: T;
  steps?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  hero: {
    title: string;
    text?: string | null;
    cta: {
      label: string;
      /**
       * « /the-estate » sur le site, ou « https://… » ailleurs.
       */
      url: string;
    };
    photoStart?: (number | null) | Media;
    /**
     * Dans l’arche.
     */
    photo?: (number | null) | Media;
    photoEnd?: (number | null) | Media;
  };
  cellar: {
    title: string;
    /**
     * Dans cet ordre, autant qu’il en faut. La boutique les montre aussi en premier, triée par « Nos préférés », et le panier les propose. Sans aucun, l’accueil montre les trois derniers produits.
     */
    products?: string[] | null;
  };
  estate: {
    /**
     * Un retour à la ligne coupe le titre à cet endroit.
     */
    title: string;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Dans l’arche.
     */
    photo?: (number | null) | Media;
  };
  orchard: {
    title: string;
    text?: string | null;
    link: {
      label: string;
      /**
       * « /the-estate » sur le site, ou « https://… » ailleurs.
       */
      url: string;
    };
  };
  families: {
    title: string;
  };
  miniatures: {
    title: string;
    text?: string | null;
    facts?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    cta: {
      label: string;
      /**
       * « /the-estate » sur le site, ou « https://… » ailleurs.
       */
      url: string;
    };
  };
  awards: {
    title: string;
  };
  /**
   * Ce que montrent les moteurs de recherche et les liens partagés.
   */
  seo: {
    /**
     * Le nom de la boutique s’y ajoute : « … – Coup de Canon ».
     */
    title: string;
    description: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop".
 */
export interface Shop {
  id: number;
  hero: {
    title: string;
    /**
     * « {produits} » écrit le nombre de produits de la boutique : « 24 produits ».
     */
    text?: string | null;
  };
  quote: {
    text: string;
    caption?: string | null;
  };
  /**
   * Ce que montrent les moteurs de recherche et les liens partagés.
   */
  seo: {
    /**
     * Le nom de la boutique s’y ajoute : « … – Coup de Canon ».
     */
    title: string;
    description: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Ce qui est propre à un produit est dans Medusa, ou dans Boutique › Histoires de produits.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-page".
 */
export interface ProductPage {
  id: number;
  story: {
    makingTitle: string;
    stepsTitle: string;
  };
  details?: {
    items?:
      | {
          title: string;
          text: string;
          link?: {
            label?: string | null;
            /**
             * « /the-estate » sur le site, ou « https://… » ailleurs.
             */
            url?: string | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  tasting: {
    title: string;
    text?: string | null;
    photo?: (number | null) | Media;
  };
  related: {
    title: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "estate".
 */
export interface Estate {
  id: number;
  hero: {
    title: string;
    text?: string | null;
    /**
     * En pleine largeur.
     */
    photo?: (number | null) | Media;
  };
  family: {
    title: string;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    link: {
      label: string;
      /**
       * « /the-estate » sur le site, ou « https://… » ailleurs.
       */
      url: string;
    };
    /**
     * Dans l’arche.
     */
    photo?: (number | null) | Media;
  };
  figures: {
    text: string;
  };
  madeHere: {
    title: string;
    text?: string | null;
    /**
     * Le premier en grand, les suivants à côté.
     */
    workshops?:
      | {
          title: string;
          text: string;
          photo?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  awards: {
    title: string;
  };
  activities: {
    title: string;
    text?: string | null;
    items?:
      | {
          name: string;
          text: string;
          link: {
            label: string;
            /**
             * « /the-estate » sur le site, ou « https://… » ailleurs.
             */
            url: string;
          };
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Ce que montrent les moteurs de recherche et les liens partagés.
   */
  seo: {
    /**
     * Le nom de la boutique s’y ajoute : « … – Coup de Canon ».
     */
    title: string;
    description: string;
  };
  /**
   * Comment la page apparaît dans la recherche du site.
   */
  search: {
    summary: string;
    /**
     * Séparés par des espaces : « verger pomme poire ».
     */
    keywords?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orchard".
 */
export interface Orchard {
  id: number;
  hero: {
    title: string;
    text?: string | null;
    /**
     * Dans l’arche.
     */
    photo?: (number | null) | Media;
  };
  apples: {
    title: string;
    text?: string | null;
    /**
     * Aussi sur l’accueil.
     */
    varieties?:
      | {
          name: string;
          id?: string | null;
        }[]
      | null;
  };
  pears: {
    title: string;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    link: {
      label: string;
      /**
       * « /the-estate » sur le site, ou « https://… » ailleurs.
       */
      url: string;
    };
    photo?: (number | null) | Media;
  };
  harvest: {
    title: string;
    steps?:
      | {
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  additives: {
    title: string;
    text?: string | null;
  };
  animals: {
    title: string;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    link: {
      label: string;
      /**
       * « /the-estate » sur le site, ou « https://… » ailleurs.
       */
      url: string;
    };
    photo?: (number | null) | Media;
  };
  taste: {
    title: string;
    cta: {
      label: string;
      /**
       * « /the-estate » sur le site, ou « https://… » ailleurs.
       */
      url: string;
    };
  };
  /**
   * Ce que montrent les moteurs de recherche et les liens partagés.
   */
  seo: {
    /**
     * Le nom de la boutique s’y ajoute : « … – Coup de Canon ».
     */
    title: string;
    description: string;
  };
  /**
   * Comment la page apparaît dans la recherche du site.
   */
  search: {
    summary: string;
    /**
     * Séparés par des espaces : « verger pomme poire ».
     */
    keywords?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weddings".
 */
export interface Wedding {
  id: number;
  hero: {
    title: string;
    text?: string | null;
    ctaLabel: string;
    /**
     * Dans l’arche.
     */
    photo?: (number | null) | Media;
  };
  offer: {
    title: string;
    miniatures: {
      title: string;
      /**
       * « {prix} » écrit le prix du produit ci-dessous, tiré de la boutique : « 1,50€ ». S’il n’est plus en vente, le membre de phrase qui le contient disparaît.
       */
      text?: string | null;
      product?: string | null;
      photo?: (number | null) | Media;
    };
    drinks: {
      title: string;
      text?: string | null;
      photo?: (number | null) | Media;
    };
    venue: {
      title: string;
      text?: string | null;
      link: {
        label: string;
        /**
         * « /the-estate » sur le site, ou « https://… » ailleurs.
         */
        url: string;
      };
    };
  };
  quote: {
    title: string;
    text?: string | null;
  };
  /**
   * Ce que montrent les moteurs de recherche et les liens partagés.
   */
  seo: {
    /**
     * Le nom de la boutique s’y ajoute : « … – Coup de Canon ».
     */
    title: string;
    description: string;
  };
  /**
   * Comment la page apparaît dans la recherche du site.
   */
  search: {
    summary: string;
    /**
     * Séparés par des espaces : « verger pomme poire ».
     */
    keywords?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "help".
 */
export interface Help {
  id: number;
  hero: {
    title: string;
    text?: string | null;
  };
  /**
   * La première est ouverte à l’arrivée sur la page.
   */
  questions?:
    | {
        question: string;
        answer: string;
        /**
         * Pour y mener directement : « pickup » ouvre cette question depuis /help#pickup, comme le lien « Livraison et retrait ». En anglais, sans espaces.
         */
        anchor?: string | null;
        id?: string | null;
      }[]
    | null;
  contact: {
    title: string;
  };
  /**
   * Ce que montrent les moteurs de recherche et les liens partagés.
   */
  seo: {
    /**
     * Le nom de la boutique s’y ajoute : « … – Coup de Canon ».
     */
    title: string;
    description: string;
  };
  /**
   * Comment la page apparaît dans la recherche du site.
   */
  search: {
    summary: string;
    /**
     * Séparés par des espaces : « verger pomme poire ».
     */
    keywords?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Les pages que trouve la recherche, à côté des produits, se règlent dans l’onglet Référencement de chacune.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  /**
   * Proposées sous le champ, avant que le visiteur écrive.
   */
  suggestions?:
    | {
        term: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Le remerciement et le récapitulatif de la commande sont écrits par le site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-confirmation".
 */
export interface OrderConfirmation {
  id: number;
  /**
   * Dans l’arche, à côté du remerciement.
   */
  photo?: (number | null) | Media;
  pickupDay: {
    title: string;
    text?: string | null;
    link: {
      label: string;
      /**
       * « /the-estate » sur le site, ou « https://… » ailleurs.
       */
      url: string;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * La ligne au-dessus de l’en-tête : une remise en cours, une fermeture exceptionnelle. Vide, le bandeau disparaît.
   */
  announcement?: string | null;
  /**
   * Sur ordinateur, à gauche du logo ; la recherche, le compte et le panier sont à droite.
   */
  main?:
    | {
        label: string;
        /**
         * « /the-estate » sur le site, ou « https://… » ailleurs.
         */
        url: string;
        /**
         * Sur téléphone, si le libellé est long.
         */
        shortLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Dans le menu qui s’ouvre sur téléphone, sous la recherche.
   */
  menu?:
    | {
        label: string;
        /**
         * « /the-estate » sur le site, ou « https://… » ailleurs.
         */
        url: string;
        /**
         * Sur téléphone, si le libellé est long.
         */
        shortLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  newsletter: {
    title: string;
    text?: string | null;
    /**
     * En petit, sous le champ.
     */
    note?: string | null;
  };
  /**
   * Trois par ligne sur ordinateur. Les documents légaux s’ajoutent tout en bas.
   */
  columns?:
    | {
        title: string;
        families?: boolean | null;
        links?:
          | {
              label: string;
              /**
               * « /the-estate » sur le site, ou « https://… » ailleurs.
               */
              url: string;
              /**
               * Sur téléphone, si le libellé est long.
               */
              shortLabel?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * En bas de chaque page.
   */
  healthWarning: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "common".
 */
export interface Common {
  id: number;
  visit: {
    title: string;
    photo?: (number | null) | Media;
  };
  ageGate: {
    title: string;
    text: string;
    healthWarning: string;
    photo?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * Affichées dans le pied de page, l’aide et les e-mails.
   */
  contact: {
    phone: string;
    email: string;
    address: {
      /**
       * Facultatif : « Château de Ouézy ».
       */
      place?: string | null;
      street: string;
      postal_code: string;
      city: string;
      region?: string | null;
      /**
       * Son code : « fr ».
       */
      country_code: string;
    };
  };
  /**
   * Pour le retrait des commandes : affichés au retrait, sur le site et dans les e-mails. Un jour sans plage est fermé.
   */
  hours?: {
    monday?:
      | {
          opens: string;
          closes: string;
          id?: string | null;
        }[]
      | null;
    tuesday?:
      | {
          opens: string;
          closes: string;
          id?: string | null;
        }[]
      | null;
    wednesday?:
      | {
          opens: string;
          closes: string;
          id?: string | null;
        }[]
      | null;
    thursday?:
      | {
          opens: string;
          closes: string;
          id?: string | null;
        }[]
      | null;
    friday?:
      | {
          opens: string;
          closes: string;
          id?: string | null;
        }[]
      | null;
    saturday?:
      | {
          opens: string;
          closes: string;
          id?: string | null;
        }[]
      | null;
    sunday?:
      | {
          opens: string;
          closes: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Pour les documents légaux et les données structurées.
   */
  legal: {
    legal_name: string;
    legal_form: string;
    siren: string;
    siret: string;
    address: string;
    /**
     * « Registre national des entreprises ».
     */
    registration?: string | null;
    vat_number?: string | null;
    /**
     * Pour une société seulement.
     */
    share_capital?: string | null;
    /**
     * Par défaut, la raison sociale.
     */
    publication_director?: string | null;
  };
  /**
   * Obligatoire dans les mentions légales.
   */
  host?: {
    name?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  /**
   * Obligatoire dans les conditions générales de vente.
   */
  mediator?: {
    name?: string | null;
    website?: string | null;
    address?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        text?: T;
        cta?:
          | T
          | {
              label?: T;
              url?: T;
            };
        photoStart?: T;
        photo?: T;
        photoEnd?: T;
      };
  cellar?:
    | T
    | {
        title?: T;
        products?: T;
      };
  estate?:
    | T
    | {
        title?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        photo?: T;
      };
  orchard?:
    | T
    | {
        title?: T;
        text?: T;
        link?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  families?:
    | T
    | {
        title?: T;
      };
  miniatures?:
    | T
    | {
        title?: T;
        text?: T;
        facts?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        cta?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  awards?:
    | T
    | {
        title?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop_select".
 */
export interface ShopSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        text?: T;
      };
  quote?:
    | T
    | {
        text?: T;
        caption?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-page_select".
 */
export interface ProductPageSelect<T extends boolean = true> {
  story?:
    | T
    | {
        makingTitle?: T;
        stepsTitle?: T;
      };
  details?:
    | T
    | {
        items?:
          | T
          | {
              title?: T;
              text?: T;
              link?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              id?: T;
            };
      };
  tasting?:
    | T
    | {
        title?: T;
        text?: T;
        photo?: T;
      };
  related?:
    | T
    | {
        title?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "estate_select".
 */
export interface EstateSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        text?: T;
        photo?: T;
      };
  family?:
    | T
    | {
        title?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        link?:
          | T
          | {
              label?: T;
              url?: T;
            };
        photo?: T;
      };
  figures?:
    | T
    | {
        text?: T;
      };
  madeHere?:
    | T
    | {
        title?: T;
        text?: T;
        workshops?:
          | T
          | {
              title?: T;
              text?: T;
              photo?: T;
              id?: T;
            };
      };
  awards?:
    | T
    | {
        title?: T;
      };
  activities?:
    | T
    | {
        title?: T;
        text?: T;
        items?:
          | T
          | {
              name?: T;
              text?: T;
              link?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              id?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  search?:
    | T
    | {
        summary?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orchard_select".
 */
export interface OrchardSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        text?: T;
        photo?: T;
      };
  apples?:
    | T
    | {
        title?: T;
        text?: T;
        varieties?:
          | T
          | {
              name?: T;
              id?: T;
            };
      };
  pears?:
    | T
    | {
        title?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        link?:
          | T
          | {
              label?: T;
              url?: T;
            };
        photo?: T;
      };
  harvest?:
    | T
    | {
        title?: T;
        steps?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  additives?:
    | T
    | {
        title?: T;
        text?: T;
      };
  animals?:
    | T
    | {
        title?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        link?:
          | T
          | {
              label?: T;
              url?: T;
            };
        photo?: T;
      };
  taste?:
    | T
    | {
        title?: T;
        cta?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  search?:
    | T
    | {
        summary?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weddings_select".
 */
export interface WeddingsSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        text?: T;
        ctaLabel?: T;
        photo?: T;
      };
  offer?:
    | T
    | {
        title?: T;
        miniatures?:
          | T
          | {
              title?: T;
              text?: T;
              product?: T;
              photo?: T;
            };
        drinks?:
          | T
          | {
              title?: T;
              text?: T;
              photo?: T;
            };
        venue?:
          | T
          | {
              title?: T;
              text?: T;
              link?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
            };
      };
  quote?:
    | T
    | {
        title?: T;
        text?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  search?:
    | T
    | {
        summary?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "help_select".
 */
export interface HelpSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        text?: T;
      };
  questions?:
    | T
    | {
        question?: T;
        answer?: T;
        anchor?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        title?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  search?:
    | T
    | {
        summary?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  suggestions?:
    | T
    | {
        term?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-confirmation_select".
 */
export interface OrderConfirmationSelect<T extends boolean = true> {
  photo?: T;
  pickupDay?:
    | T
    | {
        title?: T;
        text?: T;
        link?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  announcement?: T;
  main?:
    | T
    | {
        label?: T;
        url?: T;
        shortLabel?: T;
        id?: T;
      };
  menu?:
    | T
    | {
        label?: T;
        url?: T;
        shortLabel?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  newsletter?:
    | T
    | {
        title?: T;
        text?: T;
        note?: T;
      };
  columns?:
    | T
    | {
        title?: T;
        families?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              shortLabel?: T;
              id?: T;
            };
        id?: T;
      };
  healthWarning?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "common_select".
 */
export interface CommonSelect<T extends boolean = true> {
  visit?:
    | T
    | {
        title?: T;
        photo?: T;
      };
  ageGate?:
    | T
    | {
        title?: T;
        text?: T;
        healthWarning?: T;
        photo?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  contact?:
    | T
    | {
        phone?: T;
        email?: T;
        address?:
          | T
          | {
              place?: T;
              street?: T;
              postal_code?: T;
              city?: T;
              region?: T;
              country_code?: T;
            };
      };
  hours?:
    | T
    | {
        monday?:
          | T
          | {
              opens?: T;
              closes?: T;
              id?: T;
            };
        tuesday?:
          | T
          | {
              opens?: T;
              closes?: T;
              id?: T;
            };
        wednesday?:
          | T
          | {
              opens?: T;
              closes?: T;
              id?: T;
            };
        thursday?:
          | T
          | {
              opens?: T;
              closes?: T;
              id?: T;
            };
        friday?:
          | T
          | {
              opens?: T;
              closes?: T;
              id?: T;
            };
        saturday?:
          | T
          | {
              opens?: T;
              closes?: T;
              id?: T;
            };
        sunday?:
          | T
          | {
              opens?: T;
              closes?: T;
              id?: T;
            };
      };
  legal?:
    | T
    | {
        legal_name?: T;
        legal_form?: T;
        siren?: T;
        siret?: T;
        address?: T;
        registration?: T;
        vat_number?: T;
        share_capital?: T;
        publication_director?: T;
      };
  host?:
    | T
    | {
        name?: T;
        phone?: T;
        address?: T;
      };
  mediator?:
    | T
    | {
        name?: T;
        website?: T;
        address?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collection-query_widget".
 */
export interface CollectionQueryWidget {
  data?: {
    title?: string | null;
    relatedCollection: 'media' | 'awards' | 'legal-documents' | 'families' | 'product-stories' | 'users';
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    sortField?: string | null;
    sortDirection?: ('asc' | 'desc') | null;
    limit?: number | null;
  };
  width: 'x-small' | 'small' | 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity_widget".
 */
export interface ActivityWidget {
  data?: {
    excludedCollections?: ('media' | 'awards' | 'legal-documents' | 'families' | 'product-stories' | 'users')[] | null;
  };
  width: 'x-small' | 'small' | 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ShopValue".
 */
export interface ShopValue {
  id: string;
  blockType: 'shopValue';
  /**
   * Tirée des réglages de la boutique.
   */
  value:
    | 'siteAddress'
    | 'seller'
    | 'legalName'
    | 'legalForm'
    | 'siren'
    | 'siret'
    | 'registeredOffice'
    | 'registration'
    | 'vatNumber'
    | 'shareCapital'
    | 'publicationDirector'
    | 'phone'
    | 'email'
    | 'shopAddress'
    | 'hostName'
    | 'hostAddress'
    | 'hostPhone'
    | 'mediatorName'
    | 'mediatorAddress'
    | 'mediatorWebsite';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Boxed".
 */
export interface Boxed {
  id: string;
  blockType: 'boxed';
  /**
   * Lu par les lecteurs d’écran : « Encadré relatif aux garanties légales ».
   */
  label: string;
  content: LexicalRichText<LexicalNodes_1BF9FF18>;
  blockName?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

/** @internal Core Lexical types — see @payloadcms/richtext-lexical. */
export type LexicalElementFormat = 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
export type LexicalElementDirection = ('ltr' | 'rtl') | null;

export interface SerializedLexicalElementBase<TChildren> {
  children: TChildren[];
  direction: LexicalElementDirection;
  format: LexicalElementFormat;
  indent: number;
  textFormat?: number;
  textStyle?: string;
  version: number;
}

export type LexicalTextMode = 'normal' | 'token' | 'segmented';

export interface SerializedTextNode {
  type: 'text';
  detail: number;
  format: number;
  mode: LexicalTextMode;
  style: string;
  text: string;
  version: number;
}

export interface SerializedTabNode {
  type: 'tab';
  detail: number;
  format: number;
  mode: LexicalTextMode;
  style: string;
  text: string;
  version: number;
}

export interface SerializedLineBreakNode {
  type: 'linebreak';
  version: number;
}

export interface SerializedParagraphNode<TChildren> extends SerializedLexicalElementBase<TChildren> {
  type: 'paragraph';
  textFormat: number;
  textStyle: string;
}

export type SerializedBlockNode<TFields extends { blockType: string }> = TFields extends unknown ? {
  type: 'block';
  format: LexicalElementFormat;
  version: number;
  fields: { id: string; blockName?: string | null } & Omit<TFields, 'id' | 'blockName'>;
} : never;
export type SerializedInlineBlockNode<TFields extends { blockType: string }> = TFields extends unknown ? {
  type: 'inlineBlock';
  version: number;
  fields: { id: string } & Omit<TFields, 'id'>;
} : never;

export interface LexicalLinkFields {
  [k: string]: unknown;
  doc?: {
    relationTo: string;
    value: Config['db']['defaultIDType'] | { [k: string]: unknown; id: Config['db']['defaultIDType'] };
  } | null;
  linkType: 'custom' | 'internal';
  newTab: boolean;
  url?: string;
}
export interface SerializedLinkNode<TChildren, TFields = LexicalLinkFields> extends SerializedLexicalElementBase<TChildren> {
  type: 'link';
  fields: TFields;
  id?: string;
}
export interface SerializedAutoLinkNode<TChildren, TFields = LexicalLinkFields> extends SerializedLexicalElementBase<TChildren> {
  type: 'autolink';
  fields: TFields;
}

export interface SerializedListNode<TChildren> extends SerializedLexicalElementBase<TChildren> {
  type: 'list';
  checked?: boolean;
  listType: 'number' | 'bullet' | 'check';
  start: number;
  tag: 'ul' | 'ol';
}

export interface SerializedListItemNode<TChildren> extends SerializedLexicalElementBase<TChildren> {
  type: 'listitem';
  checked?: boolean;
  value: number;
}

/** Shape of a Lexical `richText` field. */
export interface LexicalRichText<TNode> {
  root: {
    children: TNode[];
    direction: LexicalElementDirection;
    format: LexicalElementFormat;
    indent: number;
    type: 'root';
    version: number;
  };
}

export interface SerializedHeadingNode<
  TChildren,
  TTag extends 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' = 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6',
> extends SerializedLexicalElementBase<TChildren> {
  type: 'heading';
  tag: TTag;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}